### ISSUE TITLE
Rationale for ignoring `package-lock.json`

### ISSUE THREAD

**Issue by edgarrmondragon** [evidence-dev/template#3]
Hello and thanks for creating Evidence!

I just went through the process of deploying an Evidence project with Vercel and had some minor hiccups that were easily solved with these changes:

- Allow older versions of npm (`>=6.0.0`) in `package.json`
- Commit `package-lock.json` to version control

The first one I guess is more a problem with the platform using an older version of npm, but the second one I couldn't think of a reason why it shouldn't be part of this template project 🙂

**Comment by hughess** [comment]
Hi Edgar, Thanks for flagging these!

You're right about the reason for the npm versions. We don't have a great reason to exclude `package-lock.json`, so we're going to include it in the next release of the template project!

**Comment by hughess** [comment]
Fixed!

**Comment by edgarrmondragon** [comment]
Awesome, thanks @hughess!
