### ISSUE TITLE
Ensure the e2e tests run automatically when the template project version is bumped

### ISSUE THREAD

**Issue by ud3sh** [evidence-dev/template#86]
## Background
We wanted Evidence users to be able clone the template project directly (as a github template project) without having to use `degit` to start from template.  

In order to support this, we removed the .github repository action that triggered the e2e test (otherwise user projects would trigger this same action).  Note that this is not an issue with `degit` because we had a "remove file script" that removed the action on `degit` clone).

[PR](https://github.com/evidence-dev/template/commit/aa2a020682edfd93018f90e07440b997d2c36461)  to remove the repository action
[PR](https://github.com/evidence-dev/template/commit/0da0292a5febb06396f515ff4d0e36ebd2734dcd) to remove deletion of .github folder an Evidence user clones the template using `degit`  - this is less relevant.

An obvious side effect of this is that when the template project has it's version bumped, e2e tests are not triggered automatically.  We were previously using repository actions. 

This issue for finding a workaround using an alternative to repository action.

## Steps To Reproduce
1. Bump the version of the [template](https://github.com/evidence-dev/template) project by updating `package.json`

## Expected behaviour
1. Tests in the [e2e-smoke-tests](https://github.com/evidence-dev/e2e-smoke-tests) run

## Actual Behaviour
Nothing happens

## Workarounds
Watch for commits to template, and manually run the [last action](https://github.com/evidence-dev/e2e-smoke-tests/actions) in the [e2e-smoke-tests](https://github.com/evidence-dev/e2e-smoke-tests/) repo

## Acceptance Criteria
- [ ] make the e2e-smoke-tests trigger without adding any github actions to the template project

### Potential Solutions
1. Webhooks?
1. There is a discussion here => https://github.com/orgs/community/discussions/22183

**Comment by archiewood** [comment]
In the meantime, as a manual workaround, I'll kick off the e2e tests whenever I merge to template.
